### ISSUE TITLE
[Bug] GPUdash reports incorrect VRAM on cards above 4GB

### ISSUE THREAD

**Issue by m4heshd** [Mazeby/FluentDash#2]
Here's how my GTX 1070 with 8GB of VRAM shows up on the widget. Since it's reported incorrectly, all the calculations get messed up too.

![image](https://user-images.githubusercontent.com/6711514/100652697-4f4f9700-336d-11eb-8177-1fea42c02407.png)

I've actually looked around and found that this actually is an issue on Windows API side so did a little work to fix it. PR #1 will do the trick.

**Comment by maze404** [comment]
This has been solved with the upload of FluentDash11
